# Generated by Django 6.0.1 on 2026-02-04 06:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxsafe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'ordering': ['name'], 'verbose_name': 'Family Member', 'verbose_name_plural': 'Family Members'},
        ),
        migrations.AddField(
            model_name='familymember',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('SMS', 'SMS'), ('App Notification', 'App Notification')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Self', 'Self'), ('Spouse', 'Spouse'), ('Child', 'Child'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Grandparent', 'Grandparent'), ('Grandchild', 'Grandchild'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='vaccine_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('COVID-19', 'COVID-19'), ('Influenza', 'Influenza (Flu)'), ('Hepatitis B', 'Hepatitis B'), ('Hepatitis A', 'Hepatitis A'), ('MMR', 'MMR (Measles, Mumps, Rubella)'), ('Polio', 'Polio'), ('DTP', 'DTP (Diphtheria, Tetanus, Pertussis)'), ('Varicella', 'Varicella (Chickenpox)'), ('HPV', 'HPV (Human Papillomavirus)'), ('Pneumococcal', 'Pneumococcal'), ('Meningococcal', 'Meningococcal'), ('Rotavirus', 'Rotavirus'), ('Rabies', 'Rabies'), ('Typhoid', 'Typhoid'), ('Yellow Fever', 'Yellow Fever'), ('Japanese Encephalitis', 'Japanese Encephalitis'), ('BCG', 'BCG (Tuberculosis)'), ('Other', 'Other')], help_text='Name of the vaccine', max_length=100)),
                ('dose_number', models.CharField(choices=[('1st', '1st Dose'), ('2nd', '2nd Dose'), ('3rd', '3rd Dose'), ('Booster', 'Booster'), ('Single', 'Single Dose')], default='1st', help_text='Dose number (1st, 2nd, Booster, etc.)', max_length=20)),
                ('manufacturer', models.CharField(blank=True, help_text='Vaccine manufacturer (e.g., Pfizer, Moderna)', max_length=100, null=True)),
                ('batch_number', models.CharField(blank=True, help_text='Vaccine batch/lot number', max_length=50, null=True)),
                ('date_administered', models.DateField(help_text='Date the vaccine was/will be administered')),
                ('next_dose_date', models.DateField(blank=True, help_text='Date for the next dose (if applicable)', null=True)),
                ('location', models.CharField(blank=True, help_text='Location where vaccine was administered', max_length=200, null=True)),
                ('healthcare_provider', models.CharField(blank=True, help_text='Name of healthcare provider who administered the vaccine', max_length=100, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='Scheduled', help_text='Current status of the vaccination', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or side effects', null=True)),
                ('side_effects', models.TextField(blank=True, help_text='Any side effects experienced', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_member', models.ForeignKey(blank=True, help_text='The family member this vaccine is for (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='vaxsafe.familymember')),
                ('user', models.ForeignKey(help_text='The user who owns this vaccine record', on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vaccine',
                'verbose_name_plural': 'Vaccines',
                'ordering': ['-date_administered'],
                'indexes': [models.Index(fields=['user', 'date_administered'], name='vaxsafe_vac_user_id_a4504a_idx'), models.Index(fields=['status'], name='vaxsafe_vac_status_1ac528_idx')],
            },
        ),
    ]
