# Generated by Django 6.0.1 on 2026-02-04 12:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxsafe', '0002_alter_familymember_options_familymember_blood_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='News headline', max_length=300)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=300, unique=True)),
                ('category', models.CharField(choices=[('General', 'General Health'), ('COVID-19', 'COVID-19'), ('Vaccines', 'Vaccines'), ('Research', 'Research & Studies'), ('Policy', 'Health Policy'), ('Awareness', 'Public Awareness'), ('Alert', 'Health Alert')], default='General', max_length=50)),
                ('summary', models.TextField(help_text='Brief summary of the news (200-300 words)')),
                ('content', models.TextField(help_text='Full news article content')),
                ('image', models.ImageField(blank=True, help_text='Featured image for the news article', null=True, upload_to='news_images/')),
                ('source', models.CharField(blank=True, help_text='News source', max_length=200, null=True)),
                ('source_url', models.URLField(blank=True, help_text='Link to original article', null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Is this news published?')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this news on homepage?')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Publication date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.PositiveIntegerField(default=0, help_text='Number of views')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the vaccination center', max_length=255)),
                ('address', models.TextField(help_text='Full address of the center')),
                ('city', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], help_text='City where center is located', max_length=50)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254, null=True)),
                ('opening_time', models.TimeField(blank=True, help_text='Opening time', null=True)),
                ('closing_time', models.TimeField(blank=True, help_text='Closing time', null=True)),
                ('available_vaccines', models.TextField(blank=True, help_text='List of available vaccines (comma-separated)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the center currently operational?')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True)),
                ('website', models.URLField(blank=True, help_text="Center's website URL", null=True)),
                ('description', models.TextField(blank=True, help_text='Additional information about the center', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vaccination Center',
                'verbose_name_plural': 'Vaccination Centers',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='reminder',
            options={'ordering': ['-scheduled_datetime'], 'verbose_name': 'Reminder', 'verbose_name_plural': 'Reminders'},
        ),
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-created_at'], 'verbose_name': 'Update', 'verbose_name_plural': 'Updates'},
        ),
        migrations.AddField(
            model_name='reminder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='age',
            field=models.PositiveIntegerField(blank=True, help_text='Age (optional if DOB provided)', null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='blood_group',
            field=models.CharField(blank=True, help_text='Blood group (e.g., A+, O-)', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='date_time',
            field=models.DateTimeField(blank=True, help_text='Legacy field', null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(help_text='Full name of family member', max_length=100),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Self', 'Self'), ('Spouse', 'Spouse'), ('Child', 'Child'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Grandparent', 'Grandparent'), ('Grandchild', 'Grandchild'), ('Other', 'Other')], help_text='Relationship to user', max_length=50),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='vaccine_name',
            field=models.CharField(blank=True, help_text='Legacy field - use Vaccine model instead', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='completed',
            field=models.BooleanField(default=False, help_text='Has the reminder been acknowledged'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='family_member',
            field=models.CharField(help_text='Family member name', max_length=255),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='scheduled_datetime',
            field=models.DateTimeField(help_text='When to send reminder'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='vaccine_name',
            field=models.CharField(help_text='Name of vaccine', max_length=255),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['user', 'name'], name='vaxsafe_fam_user_id_f65fab_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user', 'scheduled_datetime'], name='vaxsafe_rem_user_id_ff622c_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['completed'], name='vaxsafe_rem_complet_14fa1c_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccine',
            index=models.Index(fields=['family_member'], name='vaxsafe_vac_family__6cb245_idx'),
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationcenter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_centers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-published_date', 'is_published'], name='vaxsafe_new_publish_fa6190_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['category'], name='vaxsafe_new_categor_43d13f_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinationcenter',
            index=models.Index(fields=['city', 'is_active'], name='vaxsafe_vac_city_1712d2_idx'),
        ),
    ]
