# Generated by Django 6.0.1 on 2026-04-04 10:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxsafe', '0003_news_vaccinationcenter_alter_reminder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='Short summary (optional)', null=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('campaign', 'Campaign'), ('new_vaccine', 'New Vaccine'), ('policy', 'Policy Change'), ('alert', 'Health Alert'), ('schedule', 'Schedule Update')], default='general', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vaccine Update',
                'verbose_name_plural': 'Vaccine Updates',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterModelOptions(
            name='vaccinationcenter',
            options={'ordering': ['-rating', 'name'], 'verbose_name': 'Vaccination Center', 'verbose_name_plural': 'Vaccination Centers'},
        ),
        migrations.RemoveIndex(
            model_name='vaccinationcenter',
            name='vaxsafe_vac_city_1712d2_idx',
        ),
        migrations.AddField(
            model_name='vaccinationcenter',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Is this center officially verified?', verbose_name='Verified'),
        ),
        migrations.AddField(
            model_name='vaccinationcenter',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating (0-5)', max_digits=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='address',
            field=models.TextField(help_text='Full address of the center', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='available_vaccines',
            field=models.TextField(default='COVID-19, Influenza, Hepatitis B', help_text='Comma-separated list of available vaccines', verbose_name='Available Vaccines'),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='city',
            field=models.CharField(default='Dhaka', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='closing_time',
            field=models.TimeField(default='20:00', verbose_name='Closing Time'),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this center currently operational?', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for Google Maps', max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for Google Maps', max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='name',
            field=models.CharField(help_text='Name of the vaccination center', max_length=200, verbose_name='Center Name'),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='opening_time',
            field=models.TimeField(default='08:00', verbose_name='Opening Time'),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='vaccineupdate',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccine_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='vaccinationcenter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vaccinationcenter',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vaccinationcenter',
            name='website',
        ),
    ]
