# Generated by Django 6.0.1 on 2026-04-09 13:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxsafe', '0004_vaccineupdate_alter_vaccinationcenter_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependent_name', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Guardian', 'Guardian'), ('Member', 'Member'), ('Dependent', 'Dependent')], default='Member', max_length=20)),
                ('relation', models.CharField(blank=True, max_length=50)),
                ('can_view_others', models.BooleanField(default=False)),
                ('can_edit_others', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Family Group Member',
                'verbose_name_plural': 'Family Group Members',
            },
        ),
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('role', models.CharField(default='Member', max_length=20)),
                ('relation', models.CharField(blank=True, max_length=50)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='vaccinationcenter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_centers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationcenter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationcenter',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='blood_group',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('Self', 'Self'), ('Spouse', 'Spouse'), ('Child', 'Child'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Grandparent', 'Grandparent'), ('Grandchild', 'Grandchild'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='vaccine_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='family_member',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='scheduled_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='vaccine_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='available_vaccines',
            field=models.TextField(blank=True, default='COVID-19, Influenza, Hepatitis B', help_text='Comma-separated list of available vaccines', null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='city',
            field=models.CharField(choices=[('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Khulna', 'Khulna'), ('Barisal', 'Barisal'), ('Rangpur', 'Rangpur'), ('Mymensingh', 'Mymensingh')], default='Dhaka', max_length=100),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinationcenter',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='date_administered',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='dose_number',
            field=models.CharField(choices=[('1st', '1st Dose'), ('2nd', '2nd Dose'), ('3rd', '3rd Dose'), ('Booster', 'Booster'), ('Single', 'Single Dose')], default='1st', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='vaxsafe.familymember'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='healthcare_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(choices=[('COVID-19', 'COVID-19'), ('Influenza', 'Influenza (Flu)'), ('Hepatitis B', 'Hepatitis B'), ('Hepatitis A', 'Hepatitis A'), ('MMR', 'MMR (Measles, Mumps, Rubella)'), ('Polio', 'Polio'), ('DTP', 'DTP (Diphtheria, Tetanus, Pertussis)'), ('Varicella', 'Varicella (Chickenpox)'), ('HPV', 'HPV (Human Papillomavirus)'), ('Pneumococcal', 'Pneumococcal'), ('Meningococcal', 'Meningococcal'), ('Rotavirus', 'Rotavirus'), ('Rabies', 'Rabies'), ('Typhoid', 'Typhoid'), ('Yellow Fever', 'Yellow Fever'), ('Japanese Encephalitis', 'Japanese Encephalitis'), ('BCG', 'BCG (Tuberculosis)'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='next_dose_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='side_effects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vaccineupdate',
            name='excerpt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='vaccinationcenter',
            index=models.Index(fields=['city', 'is_active'], name='vaxsafe_vac_city_1712d2_idx'),
        ),
        migrations.AddField(
            model_name='familygroup',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_families', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familygroupmember',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='vaxsafe.familygroup'),
        ),
        migrations.AddField(
            model_name='familygroupmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaxsafe.familygroup'),
        ),
        migrations.AddField(
            model_name='familyinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='familygroupmember',
            unique_together={('family', 'user')},
        ),
    ]
