# Generated by Django 6.0.1 on 2026-04-09 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxsafe', '0005_familygroup_familygroupmember_familyinvitation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vaxsafe.familygroup'),
        ),
    ]
