# Generated by Django 6.0.1 on 2026-04-12 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxsafe', '0007_notification_vaccinereminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(choices=[('COVID-19', 'COVID-19'), ('Influenza', 'Influenza (Flu)'), ('Hepatitis B', 'Hepatitis B'), ('Hepatitis A', 'Hepatitis A'), ('MMR', 'MMR (Measles, Mumps, Rubella)'), ('Polio', 'Polio'), ('DTP', 'DTP (Diphtheria, Tetanus, Pertussis)'), ('Varicella', 'Varicella (Chickenpox)'), ('HPV', 'HPV'), ('Pneumococcal', 'Pneumococcal'), ('BCG', 'BCG (Tuberculosis)'), ('Rotavirus', 'Rotavirus'), ('Typhoid', 'Typhoid'), ('Yellow Fever', 'Yellow Fever'), ('Meningococcal', 'Meningococcal'), ('Japanese Encephalitis', 'Japanese Encephalitis'), ('Rabies', 'Rabies'), ('Other', 'Other')], max_length=100)),
                ('dose_number', models.CharField(choices=[('1st', '1st Dose'), ('2nd', '2nd Dose'), ('3rd', '3rd Dose'), ('Booster', 'Booster'), ('Single', 'Single Dose')], max_length=20)),
                ('interval_days', models.PositiveIntegerField(default=0, help_text='পরের ডোজ কতদিন পর? (শেষ ডোজ হলে 0 দিন)')),
                ('description', models.TextField(blank=True, help_text='এই ডোজ সম্পর্কে নোট', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vaccine Schedule',
                'verbose_name_plural': 'Vaccine Schedules',
                'ordering': ['vaccine_name', 'dose_number'],
                'unique_together': {('vaccine_name', 'dose_number')},
            },
        ),
    ]
