# Generated by Django 6.0.1 on 2026-04-17 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxsafe', '0008_vaccineschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinereminder',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccine_reminders', to='vaxsafe.familymember'),
        ),
    ]
