# Generated by Django 6.0.1 on 2026-04-23 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxsafe', '0011_otpverification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='area',
            field=models.CharField(blank=True, choices=[('Farmgate', 'Farmgate'), ('Mirpur-10', 'Mirpur-10'), ('Banani', 'Banani'), ('Uttara', 'Uttara'), ('Other', 'Other / Not Listed')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.CharField(blank=True, choices=[('Farmgate', 'Farmgate'), ('Mirpur-10', 'Mirpur-10'), ('Banani', 'Banani'), ('Uttara', 'Uttara'), ('Other', 'Other / Not Listed')], help_text='আপনার এলাকা নির্বাচন করুন — vaccine request সঠিক Admin এর কাছে যাবে।', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('reminder', 'Vaccine Reminder'), ('update', 'Vaccine Update'), ('alert', 'General Alert'), ('request', 'Vaccine Request')], default='reminder', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaccineschedule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AreaAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, choices=[('Farmgate', 'Farmgate'), ('Mirpur-10', 'Mirpur-10'), ('Banani', 'Banani'), ('Uttara', 'Uttara'), ('Other', 'Other / Not Listed')], help_text='এই admin কোন এলাকার দায়িত্বে? Super admin হলে ফাঁকা রাখুন।', max_length=50, null=True)),
                ('is_super_admin', models.BooleanField(default=False, help_text='✅ হলে সব এলাকার request দেখতে পারবে।')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='area_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Area Admin',
                'verbose_name_plural': 'Area Admins',
            },
        ),
        migrations.CreateModel(
            name='VaccineRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('dose_number', models.CharField(blank=True, max_length=20, null=True)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.TimeField(blank=True, null=True)),
                ('area', models.CharField(choices=[('Farmgate', 'Farmgate'), ('Mirpur-10', 'Mirpur-10'), ('Banani', 'Banani'), ('Uttara', 'Uttara'), ('Other', 'Other / Not Listed')], help_text='User এর এলাকা (auto-filled from profile)', max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccine_requests', to='vaxsafe.familymember')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vaccine Request',
                'verbose_name_plural': 'Vaccine Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['area', 'status'], name='vaxsafe_vac_area_33c39d_idx'), models.Index(fields=['user', 'status'], name='vaxsafe_vac_user_id_f45888_idx')],
            },
        ),
    ]
