# Generated by Django 6.0.1 on 2026-04-23 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxsafe', '0012_otpverification_area_profile_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaadmin',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='vaccinerequest',
            name='vaxsafe_vac_area_33c39d_idx',
        ),
        migrations.RemoveIndex(
            model_name='vaccinerequest',
            name='vaxsafe_vac_user_id_f45888_idx',
        ),
        migrations.RemoveField(
            model_name='areaadmin',
            name='is_super_admin',
        ),
        migrations.RemoveField(
            model_name='areaadmin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='otpverification',
            name='area',
        ),
        migrations.AddField(
            model_name='areaadmin',
            name='admin_user',
            field=models.OneToOneField(blank=True, help_text='যে staff user কে এই এলাকার admin করা হবে', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='areaadmin',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='areaadmin',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vaccinerequest',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vaccine_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinerequest',
            name='preferred_center',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='areaadmin',
            name='area',
            field=models.CharField(choices=[('Farmgate', 'Farmgate'), ('Mirpur-10', 'Mirpur-10'), ('Banani', 'Banani'), ('Uttara', 'Uttara'), ('Central', 'Central / Other')], default='', help_text='এই admin কোন এলাকার দায়িত্বে আছেন', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('reminder', 'Vaccine Reminder'), ('update', 'Vaccine Update'), ('alert', 'General Alert')], default='reminder', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='area',
            field=models.CharField(blank=True, choices=[('Farmgate', 'Farmgate'), ('Mirpur-10', 'Mirpur-10'), ('Banani', 'Banani'), ('Uttara', 'Uttara'), ('Central', 'Central / Other')], help_text='আপনার এলাকা — Admin route করার জন্য ব্যবহৃত হবে', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vaccinerequest',
            name='admin_note',
            field=models.TextField(blank=True, help_text='Admin এর Response / Note', null=True),
        ),
        migrations.AlterField(
            model_name='vaccinerequest',
            name='preferred_date',
            field=models.DateField(blank=True, help_text='পছন্দের তারিখ', null=True),
        ),
        migrations.AlterField(
            model_name='vaccinerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaccineschedule',
            name='description',
            field=models.TextField(blank=True, help_text='এই ডোজ সম্পর্কে নোট', null=True),
        ),
        migrations.RemoveField(
            model_name='vaccinerequest',
            name='area',
        ),
        migrations.RemoveField(
            model_name='vaccinerequest',
            name='dose_number',
        ),
        migrations.RemoveField(
            model_name='vaccinerequest',
            name='preferred_time',
        ),
        migrations.RemoveField(
            model_name='vaccinerequest',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='vaccinerequest',
            name='reviewed_by',
        ),
    ]
