# Generated by Django 6.0.5 on 2026-05-10 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxsafe', '0013_alter_areaadmin_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='handoff_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='handoff_note',
            field=models.TextField(blank=True, help_text='কেন এই profile handover/inactive হয়েছে', null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False হলে এই profile আর কেউ handle করছে না — claim/transfer প্রয়োজন'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='previous_caretaker',
            field=models.ForeignKey(blank=True, help_text='যে আগে এই profile handle করত (history track করার জন্য)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handed_off_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccinationcenter',
            name='area',
            field=models.CharField(choices=[('Farmgate', 'Farmgate'), ('Mirpur-10', 'Mirpur-10'), ('Banani', 'Banani'), ('Uttara', 'Uttara'), ('Central', 'Central / Other')], default='Central', help_text='এই কেন্দ্র কোন এলাকায় অবস্থিত — Area Admin এই কেন্দ্রগুলো manage করবেন', max_length=50),
        ),
        migrations.AddIndex(
            model_name='vaccinationcenter',
            index=models.Index(fields=['area', 'is_active'], name='vaxsafe_vac_area_c3f1fd_idx'),
        ),
    ]
